#!/bin/sh
############################################################ IDENT(1)
#
# $Title: Script to make dynamic changes to nsadmin $
# $Copyright: 2019 Devin Teske. All rights reserved. $
# $FrauBSD: nsadmin/nsupd 2019-11-01 15:48:15 -0700 freebsdfrau $
#
############################################################ GLOBALS

VERSION='$Version: 0.0.2 $'

pgm="${0##*/}" # Program basename

PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin

#
# Global exit status
#
SUCCESS=0
FAILURE=1

#
# OS Glue
#
: ${UNAME_s:=$( uname -s )}

#
# Command-line options
#
LOCAL=		# -l

############################################################ FUNCTIONS

die()
{
	local fmt="$1"
	if [ $# -gt 0 ]; then
		shift 1 # fmt
		printf "%s: $fmt\n" "$pgm" "$@" >&2
	fi
	exit $FAILURE
}

usage()
{
	local optfmt="\t%-16s %s\n"
	exec >&2
	if [ $# -gt 0 ]; then
		local fmt="$1"
		shift 1 # fmt
		printf "%s: $fmt\n" "$pgm" "$@"
	fi
	printf "Usage: %s [-hlV] [ignored]\n" "$pgm"
	printf "Options:\n"
	printf "$optfmt" "-h" "Print usage statement and exit."
	printf "$optfmt" "-l" "Local-host only mode."
	printf "$optfmt" "-V" "Print version and exit."
	printf "Ignored Options (for compatibility):\n"
	printf "$optfmt" "-d" "Not implemented."
	printf "$optfmt" "-D" "Not implemented."
	printf "$optfmt" "-i" "Not implemented."
	printf "$optfmt" "-k keyfile" "Not implemented."
	printf "$optfmt" "-L level" "Not implemented."
	printf "$optfmt" "-p port" "Not implemented."
	printf "$optfmt" "-P" "Not implemented."
	printf "$optfmt" "-r udpretries" "Not implemented."
	printf "$optfmt" "-R randomdev" "Not implemented."
	printf "$optfmt" "-t timeout" "Not implemented."
	printf "$optfmt" "-T" "Not implemented."
	printf "$optfmt" "-u udptimeout" "Not implemented."
	printf "$optfmt" "-v" "Not implemented."
	printf "$optfmt" "-y [hmac:]keyname:secret" ""
	printf "$optfmt" "" "Not implemented."
	die
}

############################################################ MAIN

#
# Process command-line options
#
optign=dDik:L:p:Pr:R:t:Tu:vy:
while getopts hlV$optign flag; do
	case "$flag" in
	d|D|i|k|L|p|P|r|R|t|T|u|v|y) : ignored ;;
	l) LOCAL=1 ;;
	V) VERSION="${VERSION#*: }"
		echo "${VERSION% $}"
		exit $SUCCESS ;;
	*) usage # NOTREACHED
	esac
done
shift $(( $OPTIND - 1 ))

exit $SUCCESS

################################################################################
# END
################################################################################
